# 线上配置文件
server:
  port: 8101
  address: 0.0.0.0
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.109.130:3306/intelligentbi
    username: root
    password: 123456
  # rabbitmq 配置
  rabbitmq:
    host: 192.168.109.130
    port: 5672
    username: admin
    password: ZTbp5GFs
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 192.168.109.130
    port: 6379
    timeout: 5000
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
